<?php 
return [
    'meta'     => [
        'name'    => 'NameSilo',
        'version' => '1.0',
        'logo'    => 'logo.png',
    ],
    'settings' => [
        'whois-types'      => true,
        'doc-fields' => [
            'us'    => [
                'usnc' => [
                    'type' => 'select',
                    'name' => '.US Nexus Category',
                    'options' => [
                        'C11' => 'US Citizen',
                        'C12' => 'US Permanent Resident',
                        'C21' => 'Incorporated or organized in US',
                        'C31' => 'Foreign entity doing business in US',
                        'C32' => 'Foreign entity with office in US',
                        'P1' => 'Business for Profit',
                        'P2' => 'Non-Profit',
                        'P3' => 'Personal',
                        'P4' => 'Educational',
                        'P5' => 'Governmental',
                    ],
                ],
                'usap' => [
                    'type' => 'select',
                    'name' => '.US Application Purpose',
                    'options' => [
                        'C11' => 'US Citizen',
                        'C12' => 'US Permanent Resident',
                        'C21' => 'Incorporated or organized in US',
                        'C31' => 'Foreign entity doing business in US',
                        'C32' => 'Foreign entity with office in US',
                        'P1' => 'Business for Profit',
                        'P2' => 'Non-Profit',
                        'P3' => 'Personal',
                        'P4' => 'Educational',
                        'P5' => 'Governmental',
                    ],
                ],
            ],
            'ca'    => [
                'calf' => [
                    'type' => 'select',
                    'name' => 'CIRA Legal Form',
                    'options' => [
                        'CCO'   => 'Corporation (Canada or Canadian province or territory)',
                        'CCT'   => 'Canadian citizen',
                        'RES'   => 'Permanent Resident of Canada',
                        'GOV'   => 'Government or government entity in Canada',
                        'EDU'   => 'Canadian Educational institution',
                        'ASS'   => 'Canadian Unincorporated Association',
                        'HOP'   => 'Canadian Hospital',
                        'PRT'   => 'Partnership Registered in Canada',
                        'TDM'   => 'Trade-mark registered in Canada (by a non-Canadian owner)',
                        'TRD'   => 'Canadian Trade union',
                        'PLT'   => 'Canadian Political party',
                        'LAM'   => 'Canadian Library, Archive or Museum',
                        'TRS'   => 'Trust established in Canada',
                        'ABO'   => 'Aboriginal Peoples (individuals or groups) indigenous to Canada',
                        'INB'   => 'Indian Band recognized by the Indian Act of Canada',
                        'LGR'   => 'Legal Representative of a Canadian Citizen or Permanent Resident',
                        'OMK'   => 'Official mark registered in Canada',
                        'MAJ'   => 'Her Majesty the Queen',
                    ],
                ],
                'caln' => [
                    'type' => 'select',
                    'name' => 'CIRA Language',
                    'options' => [
                        'en'   => 'English',
                        'fr'   => 'French',
                    ],
                ],
                'caag' => [
                    'type' => 'select',
                    'name' => 'CIRA Agreement Version',
                    'options' => [
                        '2.0'   => 'Version 2.0 of the CIRA Agreement',
                    ],
                ],
                'cawd' => [
                    'type' => 'select',
                    'name' => 'CIRA WHOIS Display',
                    'options' => [
                        '1'   => 'Show information in WHOIS',
                        '0'   => 'Hide information in WHOIS',
                    ],
                ],
            ],
        ],
        'dns-record-types' => [
            'A',
            'AAAA',
            'MX',
            'CNAME',
            'TXT',
        ],
        'dns-digest-types'     => [
            1               => 'SHA-1 (1)',
            2               => 'SHA-256 (2)',
            3               => 'GOST R 34.11-94 (3)',
            4               => 'SHA-384 (4)',
        ],
        'dns-algorithms'       => [
            1               => 'RSA/MD5 (1)',
            2               => 'Diffie-Hellman (2)',
            3               => 'DSA/SHA-1 (3)',
            4               => 'Elliptic Curve (4)',
            5               => 'RSA/SHA-1 (5)',
            6               => 'DSA-NSEC3-SHA1 (6)',
            7               => 'RSASHA1-NSEC3-SHA1 (7)',
            8               => 'RSA/SHA-256 (8)',
            10               => 'RSA/SHA-512 (10)',
            12               => 'ECC-GOST (12)',
            13              => 'ECDSA Curve P-256 with SHA-256 (13)',
            14              => 'ECDSA Curve P-384 with SHA-384 (14)',
            252             => 'Indirect (252)',
            253             => 'Private DNS (253)',
            254             => 'Private OID (254)',
        ],
        'api-key'          => '',
        'api-key-sandbox'  => '',
        'payment-id'       => '',
        'coupon'           => '',
        'auto-renew'       => false,
        'test-mode'        => false,
        'whidden-amount'   => 0,
        'whidden-currency' => 4,
        'cost-currency'    => 4,
        'adp'              => false,
    ],
];
