<?php 
return [
    'meta'     => [
        'name'    => 'MrDomain',
        'version' => '1.0',
        'logo'    => 'logo.webp',
    ],
    'settings' => [
        'whois-types'       => true,
        'doc-fields'        => [
            'es' => [
                'OrgType' => [
                    'type' => 'select',
                    'name' => 'Spanish Organization Type',
                    'options' => [
                        39 => 'Agrupación de Interés Económico',
                        47 => 'Asociación',
                        59 => 'Asocicación Deportiva',
                        68 => 'Asocicación Gremial',
                        124 => 'Caja de Ahorros',
                        150 => 'Comunidad de Bienes',
                        152 => 'Comunidad de Propietarios',
                        164 => 'Congregación o Instición Religiosa',
                        878 => 'Consejo Regulador de Denominación de Origen',
                        181 => 'Consulado',
                        197 => 'Corporación de Derecho Público',
                        203 => 'Embajada',
                        229 => 'Entidad Local',
                        269 => 'Federación Deportiva',
                        286 => 'Fundación',
                        365 => 'Mutua de Seguros',
                        879 => 'Organismo Gestor de Espacio Natural',
                        745 => 'Organismo Público Autonómico',
                        746 => 'Organismo Público Estatal',
                        747 => 'Organismo Público Local',
                        434 => 'Órgano de la Administración Autonómica',
                        436 => 'Órgano de la Administración del Estado',
                        877 => 'Otras',
                        439 => 'Partido Político',
                        476 => 'Sindicato',
                        510 => 'Sociedad Agraria de Transformación',
                        524 => 'Sociedad Anónima',
                        525 => 'Sociedad Anónima Deportiva',
                        744 => 'Sociedad Anónima Laboral',
                        554 => 'Sociedad Civil',
                        560 => 'Sociedad Colectiva',
                        562 => 'Sociedad Comanditaria',
                        566 => 'Sociedad Cooperativa',
                        608 => 'Sociedad Laboral Limitada',
                        612 => 'Sociedad Limitada',
                        713 => 'Sucursal en España',
                        717 => 'Unión Temporal de Empresas',
                    ],
                ],
                'IdentNumber' => [
                    'type' => "text",
                    'name' => "Tax identification number, VAT Number, ID Card number",
                ],

            ],
            'online' =>  [
                'IdentNumber' => [
                    'type' => "text",
                    'name' => "Tax identification number, VAT Number, ID Card number",
                ],
            ],
        ],
        'hostname'          => 'https://simple-api.dondominio.net',
        'username'          => '',
        'password'          => '',
        'test-mode'         => 0,
        'whidden-amount'    => 0,
        'whidden-currency'  => 4,
        'adp'               => false,
        'cost-currency'     => 4,
    ],
];
