<?php 
return [
    'meta'     => [
        'name'    => 'Namecheap',
        'version' => '1.0',
        'logo'    => 'logo.svg',
    ],
    'settings' => [
        'whois-types'      => true,
        'dns-record-types' => [
            'A',
            'AAAA',
            'ALIAS',
            'CAA',
            'CNAME',
            'MX',
            'MXE',
            'NS',
            'TXT',
            'URL',
            'URL301',
            'FRAME',
        ],
        'doc-fields'       => [
            'us' => [
                'RegistrantNexus' => [
                    'name'          => "Nexus",
                    'description'   => "",
                    'type'          => "select",
                    'required'      => true,
                    'options' => [
                        'C11' => "C11: represents a natural person who is a US citizen",
                        'C12' => "C12: represents a natural person who is a permanent resident",
                        'C21' => "C21: represents an entity or an organization",
                        'C31' => "C31: represents a foreign organization",
                        'C32' => "C32: represents a foreign organization that has an office in US",
                    ],
                ],
                'RegistrantNexusCountry' => [
                    'name'          => "Nexus Country",
                    'description'   => "Two-digit country code, Ex:US,DE,FR",
                    'type'          => "text",
                    'required'      => false,
                ],
                'RegistrantPurpose' => [
                    'name'          => "Purpose",
                    'type'          => "select",
                    'required'      => true,
                    'options'       => [
                        'P1'            => "P1: represents a business organization",
                        'P2'            => "P2: represents a non-profit or religious organization or association",
                        'P3'            => "P3: represents personal purpose",
                        'P4'            => "P4: represents educational purpose",
                        'P5'            => "P5: represents government purpose organization, etc",
                    ],
                ],
            ],
            'eu' => [
                'EUAgreeWhoisPolicy' => [
                    'name' => "Policy",
                    'description' => "I hereby agree that the Registry is entitled to transfer the data contained in this application to third parties...",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'YES' => "YES"
                    ],
                ],
                'EUAgreeDeletePolicy' => [
                    'name' => "Delete Policy",
                    'description' => "I agree and acknowledge to the special renewal and expiration terms set forth below for this domain name...",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'YES' => "YES",
                        'NO' => "NO"
                    ],
                ],
                'EUAdrLang' => [
                    'name' => "Language",
                    'description' => "",
                    'type' => "select",
                    'required' => false,
                    'options' => [
                        'EN' => "English",
                        'BG' => "Bulgaria",
                        'CS' => "Czech",
                        'DS' => "Danish",
                        'NL' => "Dutch",
                        'ET' => "Estonian",
                        'FI' => "Finnish",
                        'FR' => "French",
                        'DE' => "German",
                        'EL' => "Greek",
                        'HU' => "Hungarian",
                        'IT' => "Italian",
                        'LV' => "Latvian",
                        'LI' => "Lithuanian",
                        'MT' => "Maltese",
                        'PL' => "Polish",
                        'RO' => "Romania",
                        'SK' => "Slovak",
                        'SL' => "Slovenian",
                        'ES' => "Spanish",
                        'SV' => "Swedish"
                    ],
                ],
            ],
            'nu' => [
                'NUOrgNo' => [
                    'name'          => "Personal Identification Number",
                    'description'   => "The Swedish Resident, should provide a valid.\n* Personal Identification Number, if registrant is an individual\n* Organization Identification Number, if the registrant is a corporation registered in Sweden.",
                    'type'          => "text",
                    'required'      => true,
                ],
                'NUvatNo' => [
                    'name'          => "Company VAT Number",
                    'description'   => "Swedish Organization in addition to Corporation ID, user can also optionally provide additional Tax/VAT Number.",
                    'type'          => "text",
                    'required'      => false,
                ],
            ],
            'ca' => [
                'CIRALegalType' => [
                    'name' => "Legal Type",
                    'description' => "Legal Type of Registrant Contact",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'CCO' => 'Corporation',
                        'CCT' => 'Canadian citizen',
                        'RES' => 'Canadian resident',
                        'GOV' => 'Government entity',
                        'EDU' => 'Educational',
                        'ASS' => 'Unincorporated Association',
                        'HOP' => 'Hospital',
                        'PRT' => 'Partnership',
                        'TDM' => 'Trade-mark',
                        'TRD' => 'Trade Union',
                        'PLT' => 'Political Party',
                        'LAM' => 'Libraries, Archives and Museums',
                        'TRS' => 'Trust',
                        'ABO' => 'Aboriginal Peoples',
                        'INB' => 'Indian Band',
                        'LGR' => 'Legal Representative',
                        'OMK' => 'Official Mark',
                        'MAJ' => 'The Queen'
                    ],
                ],
                'CIRAWhoisDisplay' => [
                    'name' => "Whois Display",
                    'description' => "Individuals (CCT, RES, ABO, LGR) may keep their Registrant contact information private in CIRA’s Whois; non-individuals must show their full Registrant information.",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'CCO' => 'CCO: Corporation',
                        'CCT' => 'CCT: Canadian citizen',
                        'RES' => 'RES: Canadian resident',
                        'GOV' => 'GOV: Government entity',
                        'EDU' => 'EDU: Educational',
                        'ASS' => 'ASS: Unincorporated Association',
                        'HOP' => 'HOP: Hospital',
                        'PRT' => 'PRT: Partnership',
                        'TDM' => 'TDM: Trade-mark',
                        'TRD' => 'TRD: Trade Union',
                        'PLT' => 'PLT: Political Party',
                        'LAM' => 'LAM: Libraries, Archives and Museums',
                        'TRS' => 'TRS: Trust',
                        'ABO' => 'ABO: Aboriginal Peoples',
                        'INB' => 'INB: Indian Band',
                        'LGR' => 'LGR: Legal Representative',
                        'OMK' => 'OMK: Official Mark',
                        'MAJ' => 'MAJ: The Queen'
                    ],
                ],
                'CIRAAgreementVersion' => [
                    'name' => "Agreement Version",
                    'description' => "Version of the CIRA Registrant Agreement to which Registrant is agreeing.",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        '2.0' => '2.0',
                    ],

                ],
                'CIRAAgreementValue' => [
                    'name' => "Agreement Value",
                    'description' => "This value should be Y (agreed to agreement) for the domain to be registered. Passing other values will fail the registration.",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'Y' => 'Yes',
                    ],

                ],
                'CIRALanguage' => [
                    'name' => "Language",
                    'description' => "Language in which to communicate with he contact. Default: English",
                    'type' => "select",
                    'required' => false,
                    'options' => [
                        'en' => 'English',
                        'fr' => 'French',
                    ],

                ],
            ],
            'co.uk' => [
                'COUKLegalType' => [
                    'name' => "Legal Type",
                    'description' => "Legal Type of Registrant Contact",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'IND' => 'IND: UK individual',
                        'FIND' => 'FIND: Non-UK individual',
                        'LTD' => 'LTD: UK Limited Company*',
                        'PLC' => 'PLC: UK Public Limited Company*',
                        'PTNR' => 'PTNR: UK Partnership',
                        'LLP' => 'LLP: UK Limited Liability Partnership*',
                        'IP' => 'IP: UK Industrial/Provident Registered Company',
                        'STRA' => 'STRA: UK Sole Trader',
                        'SCH' => 'SCH: UK School',
                        'RCHAR' => 'RCHAR: UK Registered Charity*',
                        'GOV' => 'GOV: UK Government Body',
                        'OTHER' => 'OTHER: UK Entity (other)',
                        'CRC' => 'CRC: UK Corporation by Royal Charter',
                        'FCORP' => 'FCORP: Foreign Organization',
                        'STAT' => 'STAT: UK Statutory Body FIND',
                        'FOTHER' => 'FOTHER: Other Foreign Organizations'
                    ],
                ],
                'COUKCompanyID' => [
                    'name'          => "Company Identification Number",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => false,
                ],
                'COUKRegisteredfor' => [
                    'name'          => "Company or Person the domain is registered for",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => true,
                ],
            ],
            'me.uk' => [
                'MEUKLegalType' => [
                    'name' => "Legal Type",
                    'description' => "Legal Type of Registrant Contact",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'IND' => 'IND: UK individual',
                        'FIND' => 'FIND: Non-UK individual',
                        'LTD' => 'LTD: UK Limited Company*',
                        'PLC' => 'PLC: UK Public Limited Company*',
                        'PTNR' => 'PTNR: UK Partnership',
                        'LLP' => 'LLP: UK Limited Liability Partnership*',
                        'IP' => 'IP: UK Industrial/Provident Registered Company',
                        'STRA' => 'STRA: UK Sole Trader',
                        'SCH' => 'SCH: UK School',
                        'RCHAR' => 'RCHAR: UK Registered Charity*',
                        'GOV' => 'GOV: UK Government Body',
                        'OTHER' => 'OTHER: UK Entity (other)',
                        'CRC' => 'CRC: UK Corporation by Royal Charter',
                        'FCORP' => 'FCORP: Foreign Organization',
                        'STAT' => 'STAT: UK Statutory Body',
                        'FOTHER' => 'FOTHER: Other Foreign Organizations'
                    ],
                ],
                'MEUKCompanyID' => [
                    'name'          => "Company Identification Number",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => false,
                ],
                'MEUKRegisteredfor' => [
                    'name'          => "Company or Person the domain is registered for",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => true,
                ],

            ],
            'org.uk' => [
                'ORGUKLegalType' => [
                    'name' => "Legal Type",
                    'description' => "Legal Type of Registrant Contact",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'IND' => 'IND: UK individual',
                        'FIND' => 'FIND: Non-UK individual',
                        'LTD' => 'LTD: UK Limited Company*',
                        'PLC' => 'PLC: UK Public Limited Company*',
                        'PTNR' => 'PTNR: UK Partnership',
                        'LLP' => 'LLP: UK Limited Liability Partnership*',
                        'IP' => 'IP: UK Industrial/Provident Registered Company',
                        'STRA' => 'STRA: UK Sole Trader',
                        'SCH' => 'SCH: UK School',
                        'RCHAR' => 'RCHAR: UK Registered Charity*',
                        'GOV' => 'GOV: UK Government Body',
                        'OTHER' => 'OTHER: UK Entity (other)',
                        'CRC' => 'CRC: UK Corporation by Royal Charter',
                        'FCORP' => 'FCORP: Foreign Organization',
                        'STAT' => 'STAT: UK Statutory Body',
                        'FOTHER' => 'FOTHER: Other Foreign Organizations'
                    ],
                ],
                'ORGUKCompanyID' => [
                    'name'          => "Company Identification Number",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => false,
                ],
                'ORGUKRegisteredfor' => [
                    'name'          => "Company or Person the domain is registered for",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => true,
                ],
            ],
            'com.au' => [
                'COMAURegistrantIdType' => [
                    'name' => "The registrant type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'ABN' => 'ABN: Australian Business Number',
                        'ACN' => 'ACN: Australian Company Number',
                        'RBN' => 'RBN: Business Registration Number',
                        'TM' => 'TM: Trademark Number',
                    ],
                ],
                'COMAURegistrantId' => [
                    'name'          => "Id of the registrant",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => true,
                ],
            ],
            'net.au' => [
                'NETAURegistrantIdType' => [
                    'name' => "The registrant type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'ABN' => 'ABN: Australian Business Number',
                        'ACN' => 'ACN: Australian Company Number',
                        'RBN' => 'RBN: Business Registration Number',
                        'TM' => 'TM: Trademark Number',
                    ],
                ],
                'NETAURegistrantId' => [
                    'name'          => "Id of the registrant",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => true,
                ],
            ],
            'org.au' => [
                'ORGAURegistrantIdType' => [
                    'name' => "The registrant type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'ABN' => 'ABN: Australian Business Number',
                        'ACN' => 'ACN: Australian Company Number',
                        'RBN' => 'RBN: Business Registration Number',
                        'TM' => 'TM: Trademark Number',
                    ],
                ],
                'ORGAURegistrantId' => [
                    'name'          => "Id of the registrant",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => true,
                ],
            ],
            'es' => [
                'ESRegistrantIdType' => [
                    'name' => "The registrant type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'ALIENID' => 'ALIENID',
                        'GENERICID' => 'GENERICID',
                        'VATID' => 'VATID'
                    ],
                ],
                'ESRegistrantId' => [
                    'name'          => "Id of the registrant",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => true,
                ],
                'ESLegalFormType' => [
                    'name' => "The legal form type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'Association' => 'Association',
                        'CentralGovernmentBody' => 'CentralGovernmentBody',
                        'CivilSociety' => 'CivilSociety',
                        'CommunityofOwners' => 'CommunityofOwners',
                        'CommunityProperty' => 'CommunityProperty',
                        'Consulate' => 'Consulate',
                        'Cooperative' => 'Cooperative',
                        'DesignationofOriginSupervisoryCouncil' => 'DesignationofOriginSupervisoryCouncil',
                        'EconomicInterestGroup' => 'EconomicInterestGroup',
                        'Embassy' => 'Embassy',
                        'EntityManagingNaturalAreas' => 'EntityManagingNaturalAreas',
                        'FarmPartnership' => 'FarmPartnership',
                        'Foundation' => 'Foundation',
                        'GeneralandLimitedPartnership' => 'GeneralandLimitedPartnership',
                        'GeneralPartnership' => 'GeneralPartnership',
                        'Individual' => 'Individual',
                        'LimitedCompany' => 'LimitedCompany',
                        'LocalAuthority' => 'LocalAuthority',
                        'LocalPublicEntity' => 'LocalPublicEntity',
                        'MutualInsuranceCompany' => 'MutualInsuranceCompany',
                        'NationalPublicEntity' => 'NationalPublicEntity',
                        'OrderorReligiousInstitution' => 'OrderorReligiousInstitution',
                        'Others' => 'Others',
                        'PoliticalParty' => 'PoliticalParty',
                        'ProfessionalAssociation' => 'ProfessionalAssociation',
                        'PublicLawAssociation' => 'PublicLawAssociation',
                        'PublicLimitedCompany' => 'PublicLimitedCompany',
                        'RegionalGovernmentBody' => 'RegionalGovernmentBody',
                        'RegionalPublicEntity' => 'RegionalPublicEntity',
                        'SavingsBank' => 'SavingsBank',
                        'SpanishOffice' => 'SpanishOffice',
                        'SportsAssociation' => 'SportsAssociation',
                        'Sports_Association' => 'Sports_Association',
                        'SportsFederation' => 'SportsFederation',
                        'TemporaryAllianceofEnterprises' => 'TemporaryAllianceofEnterprises',
                        'TradeUnion' => 'TradeUnion',
                        'WorkerownedCompany' => 'WorkerownedCompany',
                        'WorkerownedLimitedCompany' => 'WorkerownedLimitedCompany'
                    ],
                ],
                'ESAdminIdType' => [
                    'name' => "Admin ID type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'GENERICID' => "GENERICID",
                        'NATIONALIDENTITY' => "NATIONALIDENTITY",
                        'ALIENID' => "ALIENID",
                    ],
                ],
                'EsAdminID' => [
                    'name'          => "ID of the Admin",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => true,
                ],
                'ESAcceptAgreement' => [
                    'name' => "Accept Agreement",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'Yes' => "Yes",
                        'No' => "No",
                    ],
                ],
            ],
            'nom.es' => [
                'NOMESRegistrantIdType' => [
                    'name' => "The registrant type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'ALIENID' => 'ALIENID',
                        'GENERICID' => 'GENERICID',
                        'VATID' => 'VATID'
                    ],
                ],
                'NOMESRegistrantId' => [
                    'name'          => "Id of the registrant",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => true,
                ],
                'NOMESLegalFormType' => [
                    'name' => "The legal form type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'Association' => 'Association',
                        'CentralGovernmentBody' => 'CentralGovernmentBody',
                        'CivilSociety' => 'CivilSociety',
                        'CommunityofOwners' => 'CommunityofOwners',
                        'CommunityProperty' => 'CommunityProperty',
                        'Consulate' => 'Consulate',
                        'Cooperative' => 'Cooperative',
                        'DesignationofOriginSupervisoryCouncil' => 'DesignationofOriginSupervisoryCouncil',
                        'EconomicInterestGroup' => 'EconomicInterestGroup',
                        'Embassy' => 'Embassy',
                        'EntityManagingNaturalAreas' => 'EntityManagingNaturalAreas',
                        'FarmPartnership' => 'FarmPartnership',
                        'Foundation' => 'Foundation',
                        'GeneralandLimitedPartnership' => 'GeneralandLimitedPartnership',
                        'GeneralPartnership' => 'GeneralPartnership',
                        'Individual' => 'Individual',
                        'LimitedCompany' => 'LimitedCompany',
                        'LocalAuthority' => 'LocalAuthority',
                        'LocalPublicEntity' => 'LocalPublicEntity',
                        'MutualInsuranceCompany' => 'MutualInsuranceCompany',
                        'NationalPublicEntity' => 'NationalPublicEntity',
                        'OrderorReligiousInstitution' => 'OrderorReligiousInstitution',
                        'Others' => 'Others',
                        'PoliticalParty' => 'PoliticalParty',
                        'ProfessionalAssociation' => 'ProfessionalAssociation',
                        'PublicLawAssociation' => 'PublicLawAssociation',
                        'PublicLimitedCompany' => 'PublicLimitedCompany',
                        'RegionalGovernmentBody' => 'RegionalGovernmentBody',
                        'RegionalPublicEntity' => 'RegionalPublicEntity',
                        'SavingsBank' => 'SavingsBank',
                        'SpanishOffice' => 'SpanishOffice',
                        'SportsAssociation' => 'SportsAssociation',
                        'Sports_Association' => 'Sports_Association',
                        'SportsFederation' => 'SportsFederation',
                        'TemporaryAllianceofEnterprises' => 'TemporaryAllianceofEnterprises',
                        'TradeUnion' => 'TradeUnion',
                        'WorkerownedCompany' => 'WorkerownedCompany',
                        'WorkerownedLimitedCompany' => 'WorkerownedLimitedCompany'
                    ],
                ],
            ],
            'com.es' => [
                'COMESRegistrantIdType' => [
                    'name' => "The registrant type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'ALIENID' => 'ALIENID',
                        'GENERICID' => 'GENERICID',
                        'VATID' => 'VATID'
                    ],
                ],
                'COMESRegistrantId' => [
                    'name'          => "Id of the registrant",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => true,
                ],
                'COMESLegalFormType' => [
                    'name' => "The legal form type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'Association' => 'Association',
                        'CentralGovernmentBody' => 'CentralGovernmentBody',
                        'CivilSociety' => 'CivilSociety',
                        'CommunityofOwners' => 'CommunityofOwners',
                        'CommunityProperty' => 'CommunityProperty',
                        'Consulate' => 'Consulate',
                        'Cooperative' => 'Cooperative',
                        'DesignationofOriginSupervisoryCouncil' => 'DesignationofOriginSupervisoryCouncil',
                        'EconomicInterestGroup' => 'EconomicInterestGroup',
                        'Embassy' => 'Embassy',
                        'EntityManagingNaturalAreas' => 'EntityManagingNaturalAreas',
                        'FarmPartnership' => 'FarmPartnership',
                        'Foundation' => 'Foundation',
                        'GeneralandLimitedPartnership' => 'GeneralandLimitedPartnership',
                        'GeneralPartnership' => 'GeneralPartnership',
                        'Individual' => 'Individual',
                        'LimitedCompany' => 'LimitedCompany',
                        'LocalAuthority' => 'LocalAuthority',
                        'LocalPublicEntity' => 'LocalPublicEntity',
                        'MutualInsuranceCompany' => 'MutualInsuranceCompany',
                        'NationalPublicEntity' => 'NationalPublicEntity',
                        'OrderorReligiousInstitution' => 'OrderorReligiousInstitution',
                        'Others' => 'Others',
                        'PoliticalParty' => 'PoliticalParty',
                        'ProfessionalAssociation' => 'ProfessionalAssociation',
                        'PublicLawAssociation' => 'PublicLawAssociation',
                        'PublicLimitedCompany' => 'PublicLimitedCompany',
                        'RegionalGovernmentBody' => 'RegionalGovernmentBody',
                        'RegionalPublicEntity' => 'RegionalPublicEntity',
                        'SavingsBank' => 'SavingsBank',
                        'SpanishOffice' => 'SpanishOffice',
                        'SportsAssociation' => 'SportsAssociation',
                        'Sports_Association' => 'Sports_Association',
                        'SportsFederation' => 'SportsFederation',
                        'TemporaryAllianceofEnterprises' => 'TemporaryAllianceofEnterprises',
                        'TradeUnion' => 'TradeUnion',
                        'WorkerownedCompany' => 'WorkerownedCompany',
                        'WorkerownedLimitedCompany' => 'WorkerownedLimitedCompany'
                    ],
                ],
            ],
            'org.es' => [
                'ORGESRegistrantIdType' => [
                    'name' => "The registrant type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'ALIENID' => 'ALIENID',
                        'GENERICID' => 'GENERICID',
                        'VATID' => 'VATID'
                    ],
                ],
                'ORGESRegistrantId' => [
                    'name'          => "Id of the registrant",
                    'description'   => "",
                    'type'          => "text",
                    'required'      => true,
                ],
                'ORGESLegalFormType' => [
                    'name' => "The legal form type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'Association' => 'Association',
                        'CentralGovernmentBody' => 'CentralGovernmentBody',
                        'CivilSociety' => 'CivilSociety',
                        'CommunityofOwners' => 'CommunityofOwners',
                        'CommunityProperty' => 'CommunityProperty',
                        'Consulate' => 'Consulate',
                        'Cooperative' => 'Cooperative',
                        'DesignationofOriginSupervisoryCouncil' => 'DesignationofOriginSupervisoryCouncil',
                        'EconomicInterestGroup' => 'EconomicInterestGroup',
                        'Embassy' => 'Embassy',
                        'EntityManagingNaturalAreas' => 'EntityManagingNaturalAreas',
                        'FarmPartnership' => 'FarmPartnership',
                        'Foundation' => 'Foundation',
                        'GeneralandLimitedPartnership' => 'GeneralandLimitedPartnership',
                        'GeneralPartnership' => 'GeneralPartnership',
                        'Individual' => 'Individual',
                        'LimitedCompany' => 'LimitedCompany',
                        'LocalAuthority' => 'LocalAuthority',
                        'LocalPublicEntity' => 'LocalPublicEntity',
                        'MutualInsuranceCompany' => 'MutualInsuranceCompany',
                        'NationalPublicEntity' => 'NationalPublicEntity',
                        'OrderorReligiousInstitution' => 'OrderorReligiousInstitution',
                        'Others' => 'Others',
                        'PoliticalParty' => 'PoliticalParty',
                        'ProfessionalAssociation' => 'ProfessionalAssociation',
                        'PublicLawAssociation' => 'PublicLawAssociation',
                        'PublicLimitedCompany' => 'PublicLimitedCompany',
                        'RegionalGovernmentBody' => 'RegionalGovernmentBody',
                        'RegionalPublicEntity' => 'RegionalPublicEntity',
                        'SavingsBank' => 'SavingsBank',
                        'SpanishOffice' => 'SpanishOffice',
                        'SportsAssociation' => 'SportsAssociation',
                        'Sports_Association' => 'Sports_Association',
                        'SportsFederation' => 'SportsFederation',
                        'TemporaryAllianceofEnterprises' => 'TemporaryAllianceofEnterprises',
                        'TradeUnion' => 'TradeUnion',
                        'WorkerownedCompany' => 'WorkerownedCompany',
                        'WorkerownedLimitedCompany' => 'WorkerownedLimitedCompany'
                    ],
                ],
            ],
            'de'     => [
                'DEConfirmAddress' => [
                    'name' => "Confirm Address",
                    'description' => "To confirm the Administrative address is a valid German address",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'DE' => "DE",
                    ],
                ],
                'DEAgreeDelete' => [
                    'name' => "Agree Delete",
                    'description' => "To agree the renewal terms for the domain name",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'Yes' => "Yes",
                        'No' => "No",
                    ],
                ],
            ],
            'fr'     => [
                'FRLegalType' => [
                    'name' => "Registrant type",
                    'description' => "",
                    'type' => "select",
                    'required' => true,
                    'options' => [
                        'Company' => "Company",
                        'Individual' => "Individual",
                    ],
                ],
                'FRRegistrantBirthDate' => [
                    'name'          => "Registrant Birth Date",
                    'description'   => "Required only when Registrant Type = Individual",
                    'type'          => "text",
                    'required'      => false,
                ],
                'FRRegistrantBirthplace' => [
                    'name'          => "Registrant Birthplace",
                    'description'   => "Required only when Registrant Type = Individual",
                    'type'          => "text",
                    'required'      => false,
                ],
                'FRRegistrantLegalId' => [
                    'name'          => "Registrant Legal ID",
                    'description'   => "Required only when Registrant Type = Company. French company with a SIREN or SIRET number should continue to provide this number instead as legal id. The SIREN number is the first part of the SIRET NUMBER and consists of 9 digits. The SIRET number is a unique identification number with 14 digits.",
                    'type'          => "text",
                    'required'      => false,
                ],
                'FRRegistrantTradeNumber' => [
                    'name'          => "Registrant Trade Number",
                    'description'   => "Required only when Registrant Type = Company. Companies with a European trademark:For companies with a European trademark can additionally add their trademark number using this extension.",
                    'type'          => "text",
                    'required'      => false,
                ],
                'FRRegistrantDunsNumber' => [
                    'name'          => "Registrant Duns Number",
                    'description'   => "Required only when Registrant Type = Company. The DUNS number is a nine-digit number, issued by Dun Bradstreet. DUNS is the abbreviation of Data Universal Numbering System. Companies with a valid DUNS number are still obliged having their head office in the territory of the European Union. The DUNS number can be provided using this extension.",
                    'type'          => "text",
                    'required'      => false,
                ],
                'FRRegistrantLocalId' => [
                    'name'          => "Registrant Local ID",
                    'description'   => "Required only when Registrant Type = Company. Companies with a local identifier specific to a country of the European Economic Area can provide their local identifier using this extension.",
                    'type'          => "text",
                    'required'      => false,
                ],
                'FRRegistrantJoDateDec' => [
                    'name'          => "Registrant Job Date Dec",
                    'description'   => "Required only when Registrant Type = Company. French associations listed with the Journal Officiel de la République Francaise - The official gazette of the French Republic: The Journal Official Associations publishes notices of creations, breakup or substantial changes with nonprofit associations in France. Using the website http://www.societe.com and the database they provide, query for the respective data below to register a .FR domain name. - The date of declaration of the association in the form YYYY-MM-DD",
                    'type'          => "text",
                    'required'      => false,
                ],
                'FRRegistrantJoDatePub' => [
                    'name'          => "Registrant Job Date Pub",
                    'description'   => "Required only when Registrant Type = Company. The date of publication in the Journal Official in the form YYYY-MM-DD",
                    'type'          => "text",
                    'required'      => false,
                ],
                'FRRegistrantJoNumber' => [
                    'name'          => "Registrant Job Number",
                    'description'   => "Required only when Registrant Type = Company. The number of the Journal Official",
                    'type'          => "text",
                    'required'      => false,
                ],
                'FRRegistrantJoPage' => [
                    'name'          => "Registrant Job Page",
                    'description'   => "Required only when Registrant Type = Company. The page of the announcement in the Journal Official",
                    'type'          => "text",
                    'required'      => false,
                ],


            ],
        ],
        'username'         => '',
        'api-key'          => '',
        'username-sandbox' => '',
        'api-key-sandbox'  => '',
        'coupon'           => '',
        'test-mode'        => false,
        'whidden-amount'   => 0,
        'whidden-currency' => 4,
        'cost-currency'    => 4,
        'adp'              => false,
    ],
];
